### ISSUE TITLE
主从表，主表更新，从表有新增数据的时候报错

### ISSUE THREAD

**Issue by morrislchg** [APIJSON/apijson-framework#6]
主从表更新，如果从表有新增的数据就会报错。版本：4.7.1 报错信息：
```java
java.lang.UnsupportedOperationException: 写操作请求必须带条件！！！
	at apijson.orm.AbstractSQLConfig.getWhereString(AbstractSQLConfig.java:1862)
	at apijson.orm.AbstractSQLConfig.getWhereString(AbstractSQLConfig.java:1666)
	at apijson.orm.AbstractSQLConfig.getSQL(AbstractSQLConfig.java:2652)
	at apijson.orm.AbstractSQLConfig.getSQL(AbstractSQLConfig.java:2619)
	at apijson.orm.AbstractSQLExecutor.execute(AbstractSQLExecutor.java:153)
	at apijson.orm.AbstractParser.executeSQL(AbstractParser.java:1617)
	at apijson.orm.AbstractObjectParser.onSQLExecute(AbstractObjectParser.java:853)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:719)
	at apijson.orm.AbstractObjectParser.executeSQL(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:848)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:523)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:256)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:842)
	at apijson.orm.AbstractObjectParser.onChildParse(AbstractObjectParser.java:523)
	at apijson.orm.AbstractObjectParser.onTableArrayParse(AbstractObjectParser.java:628)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:262)
	at apijson.orm.AbstractObjectParser.parse(AbstractObjectParser.java:44)
	at apijson.orm.AbstractParser.onObjectParse(AbstractParser.java:842)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:398)
	at apijson.framework.APIJSONParser.parseResponse(APIJSONParser.java:92)
	at apijson.orm.AbstractParser.parseResponse(AbstractParser.java:327)
	at apijson.orm.AbstractParser.parse(AbstractParser.java:299)
	at apijson.framework.APIJSONController.parse(APIJSONController.java:80)
	at apijson.framework.APIJSONController.put(APIJSONController.java:142)
```

**Comment by TommyLemon** [comment]
请去主项目提问，按模板填写必要的信息
https://github.com/Tencent/APIJSON
